### ISSUE TITLE
Znaleźć miejsca, z których będziemy wyciągać rzepak

### ISSUE THREAD

**Issue by okcze** [Winkielek/projekt_interdyscyplinarny_arimr#1]
@okcze @MaroonBlue

**Comment by okcze** [comment]
### Efekty mojego pierwszego podejścia do tematu:
- lista znalezionych działek [arkusz](https://docs.google.com/spreadsheets/d/1lrX2c4Nv1p2zczoKqtWQsuVWIR3OZ9-zLm8szqXhQvc/edit?usp=sharing) (na razie 20, zrobienie więcej do ogarnięcia, ale kwestia ile będzie potrzebne, to tak na początek)
- dla każdej działki zapisałem: współrzędne geograficzne (środek pola/działki), datę zdjęcia z sentinel2, orientacyjny region
### Jak to robiłem?
Jednocześnie korzystałem z sentinela, [geoportal.gov.pl](https://mapy.geoportal.gov.pl/imap/Imgp_2.html) i google maps 

1. Szukam pola rzepaku na sentinelu (daty z kwitnienia rzepaku, mało chmur)
2. Lokalizuję znaleziony rzepak jednocześnie na geoportal + google
3. Sprawdzam jak wygląda to miejsce na geoportal, często coś wyglądające jak jednolite pole rzepaku składa się z kilku działek
4. Dla działki (czyli czasami kawałka całej uprawy) pobieram współrzędne z jej środka/centrum korzystając z google maps (w google maps było mi najwygodniej je sobie skopiować z konkretnego miejsca gdzie dałem pinezkę)

### Potencjalne problemy
- uprawa jest często podzielona na wiele działek, na satelicie wygląda jak jedno pole (np. może to wymusić później docinanie zdjęć treningowych do konkretnej działki itp.)
- nie znalazłem żadnego większego spisu etc. miejsc z uprawą rzepaku
- stąd cały proces u mnie w pełni ręczny

**Comment by jjanborowka** [comment]
Najlepiej było by zapisywać identyfikatory działek (numery).

**Comment by okcze** [comment]
Do znajdowanych działek zapisujmy też numer ewidencyjny działki

**Comment by okcze** [comment]
+30 działek [50/50]

**Comment by m-majchrzak** [comment]
Moje 50 działek też już jest w arkuszu, także mamy komplecik.
